### ISSUE TITLE
Release `v0.3.2`

### ISSUE THREAD

**Issue by g1eny0ung** [g1eny0ung/parse_link_header#13]
@mdharm After bb9918c80a8e28a8bc62a34e911e161153df94e2, I will release `v0.3.2` if there are no subsequent changes.

**Comment by mdharm** [comment]
There is one minor code change to fix a clippy warning.  I've made some significant updates to the GitHub Workflow to run clippy, test with multiple compiler versions, and also use pre-made workflows (rather than calling `cargo` directly).

At this point, I think we're good to release with the current tip, which is dbc62de556003bc6d90553938ff3353c2aead43c

ALSO: I think we should consider publishing a Cargo.lock file in this package; that seems to be the more common thing to do.  That would necessitate changes to .gitignore as well as the cache key in the workflow (typically the hash of Cargo.lock, not Cargo.toml, is used for the key).

**Comment by g1eny0ung** [comment]
> ALSO: I think we should consider publishing a Cargo.lock file in this package; that seems to be the more common thing to do. That would necessitate changes to .gitignore as well as the cache key in the workflow (typically the hash of Cargo.lock, not Cargo.toml, is used for the key).

I actually considered this, but I ended up referring to https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries.

P.S. I reviewed a lot of rust knowledge from your commits because I haven't written for a long time, thank you very much! 🍻

**Comment by g1eny0ung** [comment]
Released: https://crates.io/crates/parse_link_header/0.3.2.
